# Generated by Django 5.0.7 on 2024-07-31 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_orders_address_alter_orders_city_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
