# Generated by Django 5.0.7 on 2024-07-31 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_orders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Orderss',
        ),
    ]
