# Generated by Django 5.0.7 on 2024-07-31 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_rename_orders_orderss'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orderss',
            new_name='Ordersss',
        ),
    ]
