# Generated by Django 5.0.7 on 2024-08-01 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_rename_orderss_ordersss'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ordersss',
        ),
    ]
