# Generated by Django 5.0.7 on 2024-08-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_orderupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='place_orders',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
