# Generated by Django 5.0.7 on 2024-08-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_place_orders_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place_orders',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
