# Generated by Django 5.0.7 on 2024-08-06 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_place_orders_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
